#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The Euler Project: problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle      Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n1)/2   1, 5, 12, 22, 35, ...
# Hexagonal     Hn=n(2n1)     1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import time
import math

# Tn = Pp = Hq
t = time.time()
for q in xrange(144,10**6):
  p = (1.0 + math.sqrt(1 + 12*(4*q**2 - 2*q)) ) / 6
  if int(p) != p: continue
  n = (-1.0 + math.sqrt(1 + 4*(3*p**2 - p)) ) / 2
  if int(n) != n: continue

  print "found!"
  break

#print n,p,q
print "Tn =", int(n*(n+1)/2)
print "time: %f s" % (time.time() - t)