#!/usr/bin/env python
#
# The Euler Project: problem 12
#
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

from decorators import benchmark
import numpy as np

@benchmark
def solve():
  def triangle(limit=1e6):
    i = 1
    triangle = 1
    while i < limit:
      yield triangle
      i += 1
      triangle += i

  def count_factors(x):
    count, limit_factor = 0, -1
    for i in xrange(1,int(np.sqrt(x))+1):
      if x%i == 0:
        count += 1
    return 2*count

  m = 0
  for t in triangle():
    m = max(m, count_factors(t))
    if m >= 500:
      print t
      break

if __name__ == '__main__':
  solve()